# Generated by Django 2.2.9 on 2020-05-21 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='clien_id',
            new_name='client',
        ),
    ]
