# Generated by Django 2.2.9 on 2020-05-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100, verbose_name='Atributo')),
                ('value', models.CharField(max_length=100, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80, verbose_name='Empresa')),
                ('nit', models.CharField(help_text='Ingrese en nit de la empresa sin código de verificación', max_length=9, verbose_name='Nit')),
                ('code', models.CharField(max_length=1, verbose_name='Código de verificación')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extranjeria'), ('PA', 'Pasaporte')], max_length=2, verbose_name='Tipo de Documento')),
                ('document', models.CharField(max_length=12, unique=True, verbose_name='Número de Documento')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido(s)')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
                ('Attribute', models.ManyToManyField(related_name='Atributos', to='core.Attribute')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Bill_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.ForeignKey(on_delete='Factura', to='core.Bill')),
                ('product_id', models.ForeignKey(on_delete='Producto', to='core.Product')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='clien_id',
            field=models.ForeignKey(on_delete='Cliente', to='core.Client'),
        ),
    ]
