# Generated by Django 2.2.9 on 2020-05-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill_Product',
            new_name='BillProduct',
        ),
    ]
